# Add 'repo' label to any root file changes
repo:
  - ./*

# Add 'test' label to any change to *.test.ts files within the source dir
test:
  - src/**/*.test.ts

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
  - any: ["src/**/*", "!src/docs/*"]

# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
frontend:
  - any: ["src/**/*.ts"]
    all: ["!src/main.ts"]
